// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: gocfl.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GocflService_Init_FullMethodName     = "/gocfl.GocflService/Init"
	GocflService_Add_FullMethodName      = "/gocfl.GocflService/Add"
	GocflService_Update_FullMethodName   = "/gocfl.GocflService/Update"
	GocflService_Create_FullMethodName   = "/gocfl.GocflService/Create"
	GocflService_Validate_FullMethodName = "/gocfl.GocflService/Validate"
	GocflService_Shutdown_FullMethodName = "/gocfl.GocflService/Shutdown"
)

// GocflServiceClient is the client API for GocflService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GocflServiceClient interface {
	// Init initializes an empty OCFL storage root.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (GocflService_InitClient, error)
	// Add adds a new object into an existing OCFL structure.
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (GocflService_AddClient, error)
	// Update adds a new version to an existing object in an OCFL structure.
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (GocflService_UpdateClient, error)
	// Create initializes an OCFL structure and adds an initial object.
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (GocflService_CreateClient, error)
	// Validate validates an OCFL storage root or a specific object.
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (GocflService_ValidateClient, error)
	// Shutdown initiates a graceful or immediate shutdown of the gRPC server.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type gocflServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGocflServiceClient(cc grpc.ClientConnInterface) GocflServiceClient {
	return &gocflServiceClient{cc}
}

func (c *gocflServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (GocflService_InitClient, error) {
	stream, err := c.cc.NewStream(ctx, &GocflService_ServiceDesc.Streams[0], GocflService_Init_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gocflServiceInitClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GocflService_InitClient interface {
	Recv() (*InitResponse, error)
	grpc.ClientStream
}

type gocflServiceInitClient struct {
	grpc.ClientStream
}

func (x *gocflServiceInitClient) Recv() (*InitResponse, error) {
	m := new(InitResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gocflServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (GocflService_AddClient, error) {
	stream, err := c.cc.NewStream(ctx, &GocflService_ServiceDesc.Streams[1], GocflService_Add_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gocflServiceAddClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GocflService_AddClient interface {
	Recv() (*AddResponse, error)
	grpc.ClientStream
}

type gocflServiceAddClient struct {
	grpc.ClientStream
}

func (x *gocflServiceAddClient) Recv() (*AddResponse, error) {
	m := new(AddResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gocflServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (GocflService_UpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &GocflService_ServiceDesc.Streams[2], GocflService_Update_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gocflServiceUpdateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GocflService_UpdateClient interface {
	Recv() (*UpdateResponse, error)
	grpc.ClientStream
}

type gocflServiceUpdateClient struct {
	grpc.ClientStream
}

func (x *gocflServiceUpdateClient) Recv() (*UpdateResponse, error) {
	m := new(UpdateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gocflServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (GocflService_CreateClient, error) {
	stream, err := c.cc.NewStream(ctx, &GocflService_ServiceDesc.Streams[3], GocflService_Create_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gocflServiceCreateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GocflService_CreateClient interface {
	Recv() (*CreateResponse, error)
	grpc.ClientStream
}

type gocflServiceCreateClient struct {
	grpc.ClientStream
}

func (x *gocflServiceCreateClient) Recv() (*CreateResponse, error) {
	m := new(CreateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gocflServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (GocflService_ValidateClient, error) {
	stream, err := c.cc.NewStream(ctx, &GocflService_ServiceDesc.Streams[4], GocflService_Validate_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gocflServiceValidateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GocflService_ValidateClient interface {
	Recv() (*ValidateResponse, error)
	grpc.ClientStream
}

type gocflServiceValidateClient struct {
	grpc.ClientStream
}

func (x *gocflServiceValidateClient) Recv() (*ValidateResponse, error) {
	m := new(ValidateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gocflServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, GocflService_Shutdown_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GocflServiceServer is the server API for GocflService service.
// All implementations must embed UnimplementedGocflServiceServer
// for forward compatibility
type GocflServiceServer interface {
	// Init initializes an empty OCFL storage root.
	Init(*InitRequest, GocflService_InitServer) error
	// Add adds a new object into an existing OCFL structure.
	Add(*AddRequest, GocflService_AddServer) error
	// Update adds a new version to an existing object in an OCFL structure.
	Update(*UpdateRequest, GocflService_UpdateServer) error
	// Create initializes an OCFL structure and adds an initial object.
	Create(*CreateRequest, GocflService_CreateServer) error
	// Validate validates an OCFL storage root or a specific object.
	Validate(*ValidateRequest, GocflService_ValidateServer) error
	// Shutdown initiates a graceful or immediate shutdown of the gRPC server.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedGocflServiceServer()
}

// UnimplementedGocflServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGocflServiceServer struct {
}

func (UnimplementedGocflServiceServer) Init(*InitRequest, GocflService_InitServer) error {
	return status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedGocflServiceServer) Add(*AddRequest, GocflService_AddServer) error {
	return status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedGocflServiceServer) Update(*UpdateRequest, GocflService_UpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedGocflServiceServer) Create(*CreateRequest, GocflService_CreateServer) error {
	return status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGocflServiceServer) Validate(*ValidateRequest, GocflService_ValidateServer) error {
	return status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedGocflServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedGocflServiceServer) mustEmbedUnimplementedGocflServiceServer() {}

// UnsafeGocflServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GocflServiceServer will
// result in compilation errors.
type UnsafeGocflServiceServer interface {
	mustEmbedUnimplementedGocflServiceServer()
}

func RegisterGocflServiceServer(s grpc.ServiceRegistrar, srv GocflServiceServer) {
	s.RegisterService(&GocflService_ServiceDesc, srv)
}

func _GocflService_Init_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GocflServiceServer).Init(m, &gocflServiceInitServer{stream})
}

type GocflService_InitServer interface {
	Send(*InitResponse) error
	grpc.ServerStream
}

type gocflServiceInitServer struct {
	grpc.ServerStream
}

func (x *gocflServiceInitServer) Send(m *InitResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GocflService_Add_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AddRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GocflServiceServer).Add(m, &gocflServiceAddServer{stream})
}

type GocflService_AddServer interface {
	Send(*AddResponse) error
	grpc.ServerStream
}

type gocflServiceAddServer struct {
	grpc.ServerStream
}

func (x *gocflServiceAddServer) Send(m *AddResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GocflService_Update_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GocflServiceServer).Update(m, &gocflServiceUpdateServer{stream})
}

type GocflService_UpdateServer interface {
	Send(*UpdateResponse) error
	grpc.ServerStream
}

type gocflServiceUpdateServer struct {
	grpc.ServerStream
}

func (x *gocflServiceUpdateServer) Send(m *UpdateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GocflService_Create_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GocflServiceServer).Create(m, &gocflServiceCreateServer{stream})
}

type GocflService_CreateServer interface {
	Send(*CreateResponse) error
	grpc.ServerStream
}

type gocflServiceCreateServer struct {
	grpc.ServerStream
}

func (x *gocflServiceCreateServer) Send(m *CreateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GocflService_Validate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ValidateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GocflServiceServer).Validate(m, &gocflServiceValidateServer{stream})
}

type GocflService_ValidateServer interface {
	Send(*ValidateResponse) error
	grpc.ServerStream
}

type gocflServiceValidateServer struct {
	grpc.ServerStream
}

func (x *gocflServiceValidateServer) Send(m *ValidateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GocflService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GocflServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GocflService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GocflServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GocflService_ServiceDesc is the grpc.ServiceDesc for GocflService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GocflService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gocfl.GocflService",
	HandlerType: (*GocflServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shutdown",
			Handler:    _GocflService_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Init",
			Handler:       _GocflService_Init_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Add",
			Handler:       _GocflService_Add_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Update",
			Handler:       _GocflService_Update_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Create",
			Handler:       _GocflService_Create_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Validate",
			Handler:       _GocflService_Validate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gocfl.proto",
}
